global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'python-api'
    static_configs:
      - targets: ['python-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'nodejs-api'
    static_configs:
      - targets: ['nodejs-api:3001']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
